title: Systems Biology Glossary
description: A glossary of computational systems biology concepts I encountered during my doctoral research.
show_downloads: true

baseurl: "/sysbio-glossary" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://paulflang.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# sysbio-glossary date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sysbio-glossary:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

# social
author: paulflang
image: /thumbnail-jumbo.png
twitter:
  username: PaulLan64523159

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
